export const data=[
    {
        icon:'icon-name',
        text:'昵称',
        info:'name',
        rows:2,
        count:10
    },
    {
        icon:'icon-sex',
        text:'性别',
        info:'sex',
        rows:2,
        count:10
    },
    {
        icon:'icon-mobile',
        text:'手机号',
        info:'mobile',
        rows:2,
        count:11
    },
    {
        icon:'icon-view',
        text:'想去景点',
        info:'view',
        rows:2,
        count:10
    },
    {
        icon:'icon-birth',
        text:'生日',
        info:'birth',
        rows:2,
        count:10
    },
    {
        icon:'icon-tab',
        text:'个性签名',
        info:'tab',
        rows:5,
        count:100
    }
]

export const tarbarList= [
    { 
        title:'',
        key:'home',
        path:'/home',
        icon:'home',
        badge:0,
        className:'icon-home',
        seclassName:'icon-home_select',
    },
    { 
        title:'',
        key:'publish',
        path:'/publish',
        icon:'publish',
        badge:0,
        className:'icon-publish',
        seclassName:'icon-publish_select',
    },
    { 
        title:'',
        key:'talk',
        path:'/talk',
        icon:'talk',
        badge:1,
        className:'icon-talk',
        seclassName:'icon-talk_select',
    },
    { 
        title:'',
        key:'center',
        icon:'center',
        path:'/center',
        badge:0,
        className:'icon-center',
        seclassName:'icon-center_select',
    },
]

export const infos = [
    {   
        text:'发布',
        name:'note',
    },
    {   
        text:'收藏',
        name:'collect',
    },
    {   
        text:'关注',
        name:'follow',
    },
    {   
        text:'评论',
        name:'comment',
    }
]  